ALTER TABLE public.souvenirs ADD COLUMN state TEXT;

CREATE TABLE public.important_places (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    image_url text,
    location point,
    state text
);